language: python
python:
  - "2.7"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - sudo rm -f /etc/boto.cfg && python manage.py test notifier
after_success:
  - coveralls
